### ISSUE TITLE
PartTips resets transform Position/Rotation/Scale changed with B9PS when open

### ISSUE THREAD

**Issue by Kari1407** [Halbann/PartTips#1]
Basically I have a B9PS that alternates between how many engines the part supports and another to add or remove the engine shielding. but to properly pick the correct meshes without one module interfering with the other, I change the location and the scale of the mesh to hide it inside the part. 
I also have another B9PS to change the position and rotation of a transform that allows different ways to dock.

When I open the Part Tips menu, those values are reset to default, as you can see in the videos (I apologize for the quality, had to compress a bit to upload to git) and are only corrected when updated again by B9PS.

https://github.com/user-attachments/assets/8322e97d-cf56-4bd1-9db4-f1a862a2431f

https://github.com/user-attachments/assets/6ab3ba37-5809-4af5-a0d0-6a2452a00b26

This appears to only happen when using `positionOffset` `rotationOffset` `scaleOffset` on a `Transform` node inside a B9PS subtype. I have not tested if this affects stock `ModulePartVariants` (which I believe offers a similar function, however I can't see the guide I always used because the forums are down)

For your own convenience, I've made a MM patch to add a B9PS module on the MK3 Shuttle Cockpit that allows you to test it.

```
@PART[mk3Cockpit_Shuttle]
{
    MODULE
	{
		name = ModuleB9PartSwitch
		moduleID = test1
		switcherDescription = test
		affectDragCubes = false

		
		SUBTYPE
		{
			name = y
			title = Default
			descriptionSummary = default position
			primaryColor = #FFFFFF
			secondaryColor = #808080

		}

		SUBTYPE
		{
			name = n
			title = Moved
			descriptionSummary = First Introduced on Ship 26
			primaryColor = #808080
			secondaryColor = #FFFFFF

		    TRANSFORM
            {
                name = cockpit
                positionOffset = 5.0, 0.0, 7.0
                rotationOffset = 180.0, 90.0, 0
                scaleOffset  = 1.5
            }
		}
	}
}
```

**Comment by Halbann** [comment]
Thanks for such a detailed report and a config to test with. I'll get back to you once I've done some testing.

**Comment by Halbann** [comment]
What's happening is that when you open the tooltip on the part, Part Tips asks the game to compile a fresh set of part info for that particular instance of the part (so that the list of modules reflects any changes the user has made via mods like RealFuels) and the game asks each module on the part for the text you see here using `GetInfo`:

![image](https://github.com/user-attachments/assets/90534a52-3a94-4f56-840f-3743299c123d)

And B9PartSwitch is using `GetInfo` to do some initialisation of the different subtypes probably with the expectation that GetInfo will only ever be called by the game at a certain time.

The call to `InitializeSubtypes()` seems to make the switcher reset.

```
public override string GetInfo()
{
    InitializeSubtypes();
    string outStr = $"<b><color=#7fdfffff>{SubtypesCount} {switcherDescriptionPlural}</color></b>";
    foreach (var subtype in subtypes)
    {
        outStr += $"\n<b>- {subtype.title}</b>";
        foreach (var resource in subtype.tankType)
            outStr += $"\n  <color=#99ff00ff>- {resource.resourceDefinition.displayName}</color>: {resource.unitsPerVolume * GetTotalVolume(subtype) :0.#}";
    }
    return outStr;
}
```

This is the full call stack from the button press in Part Tips to the part being moved by `positionOffset`.

```
> Void B9PartSwitch.PartSwitch.PartModifiers.TransformMover:Deactivate ()+0x1 at B9PartSwitch\B9PartSwitch\PartSwitch\PartModifiers\TransformMover.cs:[45:13-45:27]
Void B9PartSwitch.PartSwitch.PartModifiers.TransformMover:OnBeforeReinitializeActiveSubtype ()+0x1 at B9PartSwitch\B9PartSwitch\PartSwitch\PartModifiers\TransformMover.cs:[32:69-32:81]
Void B9PartSwitch.PartSubtype:OnBeforeReinitializeActiveSubtype ()+0x1a at B9PartSwitch\B9PartSwitch\PartSwitch\PartSubtype.cs:[241:17-241:62]
Void B9PartSwitch.ModuleB9PartSwitch:InitializeSubtypes (Boolean)+0x52 at B9PartSwitch\B9PartSwitch\PartSwitch\ModuleB9PartSwitch.cs:[424:13-424:64]
String B9PartSwitch.ModuleB9PartSwitch:GetInfo ()+0x3 at B9PartSwitch\B9PartSwitch\PartSwitch\ModuleB9PartSwitch.cs:[232:13-232:34]
Void PartLoader:CompilePartInfo (AvailablePart, Part)+0x148 at KSP-Decompiled\Assembly-CSharp\PartLoader.cs:[1205:5-1205:53]
Void PartTips.PartTips:Open (Part)+0xb1 at PartTips\Solution\PartTips\PartTips.cs:[171:13-171:70]
Void PartTips.PartTips:CheckInput ()+0x1ab at PartTips\Solution\PartTips\PartTips.cs:[137:17-137:41]
Void PartTips.PartTips:Update ()+0x2 at PartTips\Solution\PartTips\PartTips.cs:[71:13-71:26]
```

It doesn't look like B9PartSwitch has been updated in a long time and I doubt they'd update for a minor compatibility problem with a small mod so I will have to think about what to do.

**Comment by Halbann** [comment]
Here's a version of the PartTips.dll with a crude fix. Let me know if it works with your test case.

[PartTips.zip](https://github.com/user-attachments/files/17499110/PartTips.zip)

**Edit:** Here's a smarter version of the fix that I'd prefer to use if it does the job for you.

[PartTips.zip](https://github.com/user-attachments/files/17499440/PartTips.zip)

**Comment by Halbann** [comment]
@Kari1407 I’m going to assume that this solves your case and close the issue. Let me know if it’s otherwise.

**Comment by Kari1407** [comment]
oh yeah, sorry, got a bit busy with work these past few weeks, but yeah it's good
